### PR TITLE
Merge main to dev

### PR DESCRIPTION
**Pull request by SilindileShabangu**

### CODE REVIEW

**Review by Lord-Nickelbottoms — APPROVED** [review]
Conforms to clean code practices. Be sure to put files in folders such as scripts and styles to clean things up more :)

**Review by Lord-Nickelbottoms — APPROVED** [review]

**Comment by Sisamkele022** [comment]
Great job Silindile, everything looks clean and well-organised 👌

**Review by Sisamkele022 — APPROVED** [review]

**Review by Sisamkele022 — APPROVED** [review]
Nice one 👍🏾

**Comment by SilindileShabangu** [comment]
merge

**Pull request merged**
